services:
  rf_workflows:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rf_workflows
    restart: unless-stopped
    environment:
      - PORT=3555
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATAFORSEO_LOGIN=${DATAFORSEO_LOGIN}
      - DATAFORSEO_PASSWORD=${DATAFORSEO_PASSWORD}
      - APIFY_API_TOKEN=${APIFY_API_TOKEN}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - APIFY_API_TOKEN=${APIFY_API_TOKEN}
    networks:
      - regionalflat

networks:
  regionalflat:
    external: true
